[package]
name = "lib_router"
version = "0.1.0"
edition = "2021" # Allowed values are 2015, 2018, 2021
# Rust Editions: https://doc.rust-lang.org/edition-guide/index.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-husky = "1"
ordered-float = "3.0.0"
petgraph = "0.6.2"
rand = "0.8.5"
vecmath = "1.0.0"
quaternion = "0.4.1"


[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"]


[lib]
name = "lib_router"
path = "src/lib.rs"
